name=LiteLED
version=3.1.0
author=Xylopyrographer
maintainer=Xylopyrographer <xylopyrographer@gmail.com>
sentence=High performance library for driving one or more WS2812 and other types of RGB LED strips via the RMT or PARLIO peripheral.
paragraph=Provides hardware-accelerated control using either RMT or the PARLIO parallel-IO peripheral. Supports multiple independent strips; arbitrary colour orders; DMA transfers; interrupt priority; PSRAM buffer allocation; and driving multiple strips in sync. Requires an ESP32 SoC with an RMT and/or a PARLIO peripheral. Drives RGBW strips with auto white-channel calculation.
category=Display
url=https://github.com/Xylopyrographer/LiteLED
architectures=esp32
providesIncludes=LiteLED.h
